[build]
rustflags = ["-D", "warnings"]

[target.x86_64-unknown-linux-gnu]
# Linux-specific settings

[target.x86_64-apple-darwin]
# macOS-specific settings

[target.x86_64-pc-windows-msvc]
# Windows-specific settings

[alias]
docs = "doc --no-deps --document-private-items" 